# Generated by Django 4.2.5 on 2024-10-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_event_approved_event_date_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_template',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
