# Generated by Django 4.2.5 on 2024-10-26 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_event_ticket_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cus_ph',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myApp.event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_tickets',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
