# Generated by Django 4.2.5 on 2024-10-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_booking_booked_on_remove_booking_cus_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_tickets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
