# Generated by Django 4.2.5 on 2024-10-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_booking_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='download_count',
        ),
    ]
