# Generated by Django 4.2.5 on 2024-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_remove_booking_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
