# Generated by Django 4.2.5 on 2024-10-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_booking_ticket_downloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_downloaded',
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
