# Generated by Django 4.2.5 on 2024-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_number',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
