# Generated by Django 4.2.5 on 2024-11-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_booking_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booked_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
